title: anthu's GitHub Page
email: antonhuck@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://anthu.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

twitter_username: anton_huck
github_username:  anthu